CREATE TABLE `posts` (
  `id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `title` varchar(100) NOT NULL,
  `content` text NOT NULL,
  `link` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


INSERT INTO `posts` (`id`, `title`, `content`, `link`) VALUES
(1, 'How to Create and Load Model in CodeIgniter', 'In CodeIgniter Model are the PHP classes where all database related manipulation is done e.g. fetching records, insert, update, and delete records.\n\nWithin this, all data processing logic is done.', 'http://makitweb.com/how-to-create-and-load-model-in-codeigniter/'),
(2, 'Delete Multiple Selected Records with PHP', 'It is time-consuming to delete records one by one from the list.To make deletion process easier for the users by allowing them to select multiple records using checkboxes.Execute delete query according to the selected checkboxes.', 'http://makitweb.com/delete-multiple-selected-records-with-php/'),
(3, 'Live username Availability check with AngularJS in CodeIgniter', 'If there is the registration form on the website then you need to make sure that the username or email must be unique. The user will login with the selected username next time when it comes to the website.', 'http://makitweb.com/live-username-availability-check-with-angularjs-in-codeigniter/'),
(4, 'Bootstrap Datepicker Start and End date Validation', 'You can easily enable date selection to the form element using Bootstrap datepicker if you are already using Bootstrap in your page. You need to add external Bootstrap datepicker library. This allows the users to select any from the datepicker and they are not restricted.', 'http://makitweb.com/bootstrap-datepicker-start-and-end-date-validation/'),
(5, 'Remove Duplicate values from an Array in PHP', 'The array_unique() method is used to remove repeated or duplicate values from the array and return an array. It is better to use this method on the array if there is some possibility of same values or the later code in the program depends on it for example – selecting records based on ids and displaying on the screen.', 'http://makitweb.com/remove-duplicate-values-from-an-array-in-php/'),
(6, 'Add Browse Button and Upload File in TinyMCE', 'In TinyMCE editor to view image and media options in the menu or in toolbar need to load them by using plugins option while initializing. This adds them to the editor but you can load external file by passing the source path. It does not allow to browse any file within the system. The browse button easily added by defining file_picker_callback option. This only adds browse button but not allow file selection.', 'http://makitweb.com/add-browse-button-and-upload-file-tinymce/'),
(7, 'How to Get Records from Database with AngularJS in CodeIgniter', 'Data selection is required either to display information on the screen or use it for some data manipulation. If you want to get records from the MySQL database using AngularJS in CodeIgniter then you need to create a method in the controller for handling the requests and return response.', 'http://makitweb.com/how-to-get-records-from-database-with-angularjs-in-codeigniter/'),
(8, 'Connect with Multiple Databases in CodeIgniter', 'A database is one of common requirement while building the dynamic application. It uses to store related data in an organized manner. You can use more than one database in your application. If you are using CodeIgniter Framework then you need to define the database connection details separately for multiple databases and load it explicitly for performing operations on the database.', 'http://makitweb.com/connect-with-multiple-databases-in-codeigniter/'),
(9, 'How to Make Bootstrap Modal with File Upload and Preview - jQuery AJAX', 'Bootstrap Modal is a popup container which use to show various types of information on the screen. It is very flexible and user-friendly. You can display new entry or update form in it. In this tutorial, I am using Bootstrap Modal for image file upload and display preview using jQuery and AJAX.', 'http://makitweb.com/make-bootstrap-modal-file-upload-preview-jquery-ajax/'),
(10, 'Inline Table Data Edit with AngularJS and PHP', 'Live data edit on the table makes easier to update the records while viewing.\n\nFor editing values on the table, I am using textbox element. When data is modified in the element then update records in the MySQL database table using Angular and PHP.', 'http://makitweb.com/inline-table-data-edit-with-angularjs-and-php/'),
(11, 'How to Login using Instagram API with PHP', 'Instagram is one of the most popular photos sharing platform and its users are increasing day by day. Instagram provides APIs for getting the user details and use it to enable login using Instagram on the website.', 'http://makitweb.com/how-to-login-using-instagram-api-with-php/'),
(12, 'Add remove Class with ngClass in AngularJS', 'With ngClass directive, it is easier to maintain CSS classes between HTML elements dynamically. You cannot just pass the class name in ng-class like class attribute. You need to either use the $scope variable or expression for including classes on the element. In this tutorial, I am creating a demonstration to add remove class from the element.', 'http://makitweb.com/add-remove-class-with-ngclass-in-angularjs/'),
(13, 'Pass Data Between View and Controller in CodeIgniter', 'HTML form is one of the common elements within the webpage which allows the user to input data and submit it for processing. The data is also passed by URL which is good for limited and less sensitive information. In this tutorial, I show how you can pass data between view and controller.', 'http://makitweb.com/pass-data-between-view-and-controller-in-codeigniter/'),
(14, 'Load Multiple Views in one View - CodeIgniter', 'Sometimes it is required to create separate files which were common on all other pages like header and footer section of the webpage. This makes easier to maintain the pages. include statement is used to embed files in PHP. In CodeIgniter, multiple views embedded in the single view either by controller or view.', 'http://makitweb.com/load-multiple-views-in-one-view-codeigniter/'),
(15, 'How to Create and Load View in CodeIgniter', 'A view is an HTML or PHP file in the CodeIgniter which is used to display output on the browser. From where the user can interact with the website and perform actions. Views are loaded by the controller and one view can load other views on the page. In this tutorial, I create a simple demonstration where I create a view and load it from the controller.', 'http://makitweb.com/how-to-create-and-load-view-in-codeigniter/'),
(16, 'How to Import Data in MySQL with CodeIgniter', 'CSV files are easier to maintain and can be used for export and import data in the web application. For data import first, need to allow the users to browse and upload the file. In CodeIgniter, their is upload library available which makes easier to handle file uploads.In this tutorial, I import data of CSV file in MySQL database table with CodeIgniter.', 'http://makitweb.com/how-to-import-data-in-mysql-with-codeigniter/'),
(17, 'How to Change Language in TinyMCE Editor', 'TinyMCE is a WYSIWYG editor where you can edit and preview the end result of the document. In TinyMCE by default, all labels are in US English (en_US) but it is customizable to any other language using language option. There is more than 50 languages script package is available which can be downloaded and use in language defining.', 'http://makitweb.com/how-to-change-language-in-tinymce-editor/'),
(18, 'Upload Multiple Image files to the Database using PDO - PHP', 'You can store the image files in the Database table either in base64 format or its path after uploading. In the base64 method, it is not necessary to store the uploaded file on the server because it is been directly accessed with the base64 encoded value. In this tutorial, I am using PDO connection for storing multiple image files path in the MySQL database table.', 'http://makitweb.com/upload-multiple-image-files-to-the-database-using-pdo-php/'),
(19, 'Check if Checkbox is Checked or Not with AngularJS', 'In AngularJS with the model, it is easier to maintain values across elements and to define the model ng-model directive is been used. To find checkbox is been checked or not check the defined model. If it is TRUE means checkbox is been checked. In this tutorial, I will show how you can retrieve single or multiple checked checkboxes', 'http://makitweb.com/check-if-checkbox-is-checked-or-not-with-angularjs/'),
(20, 'Dynamically load content on Bootstrap Tooltip with AJAX', 'A tooltip is used to display quick information about the element and it is easy to add to the element using Bootstrap. You can specify your text or HTML content using title option. Within the tooltip, you can show content dynamically using jQuery AJAX. For this require defining an Anonymous function to handle AJAX request and get the content.', 'http://makitweb.com/dynamically-load-content-on-bootstrap-tooltip-with-ajax/'),
(21, 'How to Restrict User Access on the Website with jQuery AJAX', 'Enable disable functionality gives the administrator more control on the site. The administrator can directly control the users from its dashboard by either restrict access to some area of the site or enable disable the user. This is very efficient when there are multiple types of the user exists on the site e.g. admin, student, professor, etc. In this tutorial, I am using jQuery AJAX for this and creating an extra field on the MySQL table.', 'http://makitweb.com/how-to-restrict-user-access-on-the-website-with-jquery-ajax/'),
(22, 'Export MySQL data to CSV file in CodeIgniter', 'CSV (Comma Separated Values ) is the most popular file format for data import and export within the project. In PHP for creating CSV file, you can either use fputcsv() method or directly write the comma-separated content on the file. In this tutorial, I will show you how you can export MySQL data in CSV file format in your CodeIgniter project.', 'http://makitweb.com/export-mysql-data-to-csv-file-in-codeigniter/'),
(23, 'Table with Search and Sort using AngularJS and PHP', 'Search filter makes easier to filter the list of records and view the only required records. This saves time when there is the huge number of records are available on the list. There is already an orderBy filter is available on AngularJS which will be used for sorting the list. In this tutorial, I am filtering MySQL table records while fetching data using AngularJS and PHP.', 'http://makitweb.com/table-with-search-and-sort-using-angularjs-and-php/'),
(24, 'Make Destination Directory on File upload with PHP', 'You normally store the user selected files in the specific directory but the same directory is also used by all other users. If you are allowing to upload multiple types of files like – image, videos, doc, etc then it becomes a mess. To avoid this you can create separate directories for the store in an organized way. But for storing it in a more organized way you can dynamically create directories for each user for storing their files. This makes traversing to file easier.', 'http://makitweb.com/make-destination-directory-on-file-upload-with-php/'),
(25, 'Create a copy of MySQL Database using phpMyAdmin', 'Sometimes it requires to quickly create a clone of the MySQL database while working on the project either for the backup purpose, using it on a copy of the project or moving the project. With phpMyAdmin, this process is easier. In this tutorial, I am assuming that you already have a cPanel enabled web hosting server.', 'http://makitweb.com/create-a-copy-of-mysql-database-using-phpmyadmin/');
